/* 2015-10-15 12:16 */
window.ClickiTrackerName="gomeClicki";window.gomeClicki=window.gomeClicki||function(){(window.gomeClicki.queue=window.gomeClicki.queue||[]).push(arguments)};window.gomeClicki.start=+new Date;window.gomeClicki.debug=!0;window.gomeClicki.debugSendUrl="//sm.gome.com.cn/collect/track_err";
gomeClicki("create",-1<window.document.location.href.search("m.gome.com.cn")?"dc-2":"dc-7","auto",{clientId:function(g){for(var e;g.length;)if(e=g.shift(),e=(e=document.cookie.match("(?:^|;)\\s*"+e+"=([^;]*)"))?unescape(e[1]):void 0)return e}(["__clickidc","__c_visitor"])});
gomeClicki("set",function(){var g={};g.dimension1=function(){function g(e){var k=new Date,l=arguments;if(1<l.length){var m=l[2]||0,q=l[3]||"/",p=l[4]||0,r=l[5]||0;m&&k.setTime(k.getTime()+1E3*m);document.cookie=e+"="+escape(l[1])+(m?"; expires="+k.toGMTString():"")+("; path="+q)+(p?"; domain="+p:"")+(r?"; secure":"");return l[1]}return(k=document.cookie.match("(?:^|;)\\s*"+e+"=([^;]*)"))?unescape(k[1]):0}var e=g("cmpid"),q,k;e&&null!=e&&void 0!=e&&""!=e&&(q=e.split("^!"),k=q[q.length-1]);var l="";
q=/(^|\?|&)cmpid=([^&]*)(&|$)/;q=location.href.replace(/#$/,"").match(q);if(null!=q&&q[2]!=k)e&&null!=e&&void 0!=e&&""!=e&&(l=e+"^!"),l+=q[2];else if(null!=q||null==document.referrer||""==document.referrer||e&&null!=e&&void 0!=e&&""!=e)l=e&&null!=e&&void 0!=e&&""!=e?e:"direct";else{var e=document.referrer,l=!1,m,p;k=[];k=[["www.baidu.com","baidu"],["m.baidu.com","baidum"],["www.sogou.com","sogou"],["www.soso.com","soso"],["www.yahoo.","yahoo"],["www.google.com","google"],["www.haosou.com","360"],
["m.haosou.com","360m"],["www.youdao.com","youdao"],[".bing.com","bing"],["m.sm.cn","sm"]];var w=/[a-zA-Z0-9][-a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62})+\.?/.exec(e)[0];k[0][0]==w&&(l=!0,m=k[0][1],q=/(^|\?|&)wd=([^&]*)(&|$)/,p=e.match(q)[2]);k[1][0]==w&&(l=!0,m=k[1][1],q=/(^|\?|&)word=([^&]*)(&|$)/,p=e.match(q)[2]);for(var u=2;4>u;u++)k[u][0]==w&&(l=!0,m=k[u][1],q=/(^|\?|&)query=([^&]*)(&|$)/,p=e.match(q)[2]);k[4][0]==w&&(l=!0,m=k[4][1],q=/(^|\?|&)p=([^&]*)(&|$)/,p=e.match(q)[2]);for(u=5;u<
k.length;u++)-1!=w.indexOf(k[u][0])&&(l=!0,m=k[u][1],q=/(^|\?|&)q=([^&]*)(&|$)/,p=e.match(q)[2]);l?l="seo_"+m+"_"+p:(m=e.split("/")[2],l="gome"!=m.split(".")[1]?"yj_"+m:"direct")}m=location.hostname.split(".");g("cmpid",l,1800,null,/^\d+$/.test(m.join(""))||3>m.length?location.hostname:m.slice(1).join("."));return l}();""!=document.referrer&&(g.dimension3=document.referrer);if(-1<window.location.href.indexOf("cmpid=")){var e=document.location.search,y=document.location.hostname,m=document.location.pathname,
p=document.location.hash,k=e.replace(/^\?.*cmpid=([^&]*)(&.*)?$/i,"$1").split("_"),l="";g.dimension12=k.join("_");k.length&&(l+="&utm_campaign="+encodeURIComponent(k.shift()))&&k.length&&(l+="&utm_source="+encodeURIComponent(k.shift()))&&k.length&&(l+="&utm_medium="+encodeURIComponent(k.shift()))&&k.length&&(l+="&utm_content="+encodeURIComponent(k.shift()))&&k.length&&(l+="&utm_term="+encodeURIComponent(k.join("_")));g.location=document.location.protocol+"//"+y+m+e+l+p}"undefined"!=typeof merchantId?
g.dimension14=merchantId:"undefined"!=typeof bbcShopId&&""!=bbcShopId&&(g.dimension14=bbcShopId);"undefined"!=typeof goodsNo&&(g.dimension9=goodsNo);"undefined"!=typeof skuId&&(g.dimension13=skuId);return g}());gomeClicki("send","pageview");
!function(g,e,y){function m(){}function p(a){return"function"==typeof a}function k(a){return void 0!=a&&-1<(a.constructor+"").indexOf("String")}function l(a,b){if(k(a)&&(a=b[a]),!p(a))return m;var c=z.call(arguments,2);return function(){return a.apply(b,c.concat(z.call(arguments)))}}function r(a){var b=g.console,c=Sa,c=g[c]=g[c]||[];ca&&(ca&&k(B)&&(B+=-1<B.indexOf("?")?"&":"?",B+="f="+encodeURIComponent(a)+"&m="+encodeURIComponent(z.call(arguments,1).join(""))+"&hash="+R(),sa(B,m,!0)),c.push(z.call(arguments)),
c.length>ta&&c.splice(0,ta-c.length),b&&b.log&&p(b.log)&&(p(b.log.apply)?b.log.apply(b,arguments):b.log(arguments[0])))}function R(){return Math.round(2147483647*Math.random())}function q(a){var b,c=1,d=0;if(a)for(c=0,b=a.length-1;0<=b;b--)d=a.charCodeAt(b),c=(c<<6&268435455)+d+(d<<14),d=266338304&c,c=0!==d?c^d>>21:c;return c}function M(){for(var a,b=[],c=arguments.length,d=0;c>d;d++)a=arguments[d],0<d&&(a=0===a.indexOf("/")?a.slice(1):a),c-1>d&&(a="/"===a.slice(-1)?a.slice(0,a.length-1):a),b.push(a);
return b.join("/")}function sa(a,b,c){var d,f;try{d="_clickiv4_"+ +new Date+R(),f=g[d]=new Image,f.onload=f.onerror=function(){try{b(),f.onload=f.onerror=g[d]=y}catch(a){}},f.src=a}catch(h){try{f=e.createElement("img"),f.onload=f.onerror=function(){try{b(),f.onload=f.onerror=g[d]=y}catch(a){}},f.src=a}catch(k){c||r("createImage","error message is: ",h.message)}}}function ba(a,b,c,d){if(a){var f=e.createElement("script");f.type="text/javascript";f.async=!0;f.src=a;f.id=b;c&&(f.addEventListener?f.onload=
c:f.onreadystatechange=function(){f.readyState in{loaded:1,complete:1}&&(f.onreadystatechange=null)});d&&(f.onerror=d);a=e.getElementsByTagName("script")[0];a.parentNode.insertBefore(f,a)}}function A(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function w(a){var b=new Date,c=arguments;if(1<c.length){var d=c[2]||0,f=c[3]||"/",h=c[4]||0,g=c[5]||0;return d&&b.setTime(b.getTime()+1E3*d),e.cookie=a+"="+escape(c[1])+(d?"; expires="+b.toGMTString():"")+("; path="+
f)+(h&&"none"!=h?"; domain="+h:"")+(g?"; secure":""),c[1]}return(b=e.cookie.match("(?:^|;)\\s*"+a+"=([^;]*)"))?unescape(b[1]):0}function u(){var a=""+e.location.hostname;return 0===a.indexOf("www.")?a.substring(4):a}function Qa(a){var b=e.referrer;if(/^https?:\/\//i.test(b)){if(a)return b;a="//"+e.location.hostname;var c=b.indexOf(a);if(5===c||6===c)if(a=b.charAt(c+a.length),"/"===a||"?"===a||""===a||":"===a)return;return b}}function Ra(){var a,b,c;if((c=(c=g.navigator)?c.plugins:null)&&c.length)for(var d=
0;d<c.length&&!b;d++){var f=c[d];-1<f.name.indexOf("Shockwave Flash")&&(b=f.description)}if(!b)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=a.GetVariable("$version")}catch(e){}if(!b)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b="WIN 6,0,21,0",a.AllowScriptAccess="always",b=a.GetVariable("$version")}catch(e){}if(!b)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=a.GetVariable("$version")}catch(e){}return b&&(a=b.match(/[\d]+/g))&&3<=a.length&&(b=a[0]+"."+a[1]+
" r"+a[2]),b||void 0}function na(a,b){var c;if(1==b.length&&null!=b[0]&&"object"==typeof b[0])c=b[0];else{var d,f=0,e={};for(d=Math.min(a.length+1,b.length);d>f;f++)if("object"==typeof b[f])for(c in b[f])b[f].hasOwnProperty(c)&&(e[c]=b[f][c]);else a.length>f&&(e[a[f]]=b[f]);c=e}return c}function oa(a,b){b=b||m;sa(M(N,Ta)+"?"+a,b)}function pa(a,b){if(b=b||m,!g.XDomainRequest)return!1;var c=new g.XDomainRequest;return c.open("POST",M(N,ua)),c.onerror=function(){b()},c.onload=b,c.send(a),!0}function qa(a,
b){if(b=b||m,!g.XMLHttpRequest)return!1;var c=new g.XMLHttpRequest;return"withCredentials"in c?(c.open("POST",M(N,ua),!0),c.setRequestHeader("Content-Type","text/plain"),c.onreadystatechange=function(){4==c.readyState&&(b(),b=null)},c.send(a),!0):!1}function ra(a,b){var c,d,f,h,k=0,l=!1;if(b=b||m,f=function(){d.src="";d.parentNode&&d.parentNode.removeChild(d)},h=function(){if(!l)try{if(9<k||d.contentWindow.location.host==e.location.host){l=!0;f();var a=f;g.removeEventListener?g.removeEventListener("beforeunload",
a,!1):g.detachEvent&&g.detachEvent("onbeforeunload",a);return void b()}}catch(c){k++,setTimeout(h,200)}},e.body){a+="####==collect_path="+M(N,Ua)+"==####";a=encodeURIComponent(a);try{d=e.createElement('<iframe name="'+a+'"></iframe>')}catch(q){d=e.createElement("iframe"),d.name=a}d.height="0";d.width="0";d.style.display="none";d.style.visibility="hidden";c=M(N,Va)+"#";c+=encodeURIComponent(e.location.protocol+"//"+e.location.host+"/favicon.ico");A(g,"beforeunload",f);A(d,"load",h);e.body.appendChild(d);
d.src=c}else{var n=arguments,p=arguments.callee;setTimeout(function(){p.apply(g,n)},100)}}function O(){this.keys=[];this.t1={};this.t2={}}function D(a,b,c,d,f){this.name=a;this.protocolParameter=b;this.defaultValue=c;this.getter=d;this.setter=f}function h(a,b,c,d,f){a=new D(a,b,c,d,f);return P.set(a.name,a),a.name}function I(a,b){da.push([new RegExp("^"+a+"$"),b])}function v(a,b,c){return h(a,b,c,void 0,m)}function va(a){var b=P.get(a);if(!b)for(var c=0;c<da.length;c++){var d=da[c],f=d[0].exec(a);
f&&(b=d[1](f),P.set(b.name,b))}return b}function Wa(a){var b;return P.map(function(c,d){d.protocolParameter==a&&(b=c)}),b}function J(a,b){var c=a.get(b);return void 0==c?"":""+c}function wa(a,b){var c=a.get(b);return void 0==c?0:1*c}function S(){var a=this;return a&&a.hasOwnProperty&&a instanceof S||(a=new S,a.init()),a}function T(){this.data=new O}function ea(){this.stack=[]}function Xa(){var a=e.location.protocol;if("http:"!=a&&"https:"!=a)throw r("checkProtocolTask","current protocol is:",a),"abort";
}function xa(a){if("cookie"===J(a,ya)){var b=[],c=a.get(U),d,f=a.get(fa);d=(1<f.length&&f.lastIndexOf("/")==f.length-1&&(f=f.substr(0,f.length-1)),0!==f.indexOf("/")&&(f="/"+f),f);var f=a.get(K),f=0===f.indexOf(".")?f.substr(1):f,e=a.get(ga),h=J(a,L),g=u().split(".");if("auto"!=f&&(w(c,h,e,d,f),w(c)==h))return void(V=!0);if(4==g.length&&0<g[g.length-1])b=["none"];else{for(var k=g.length-2;0<=k;k--)b.push(g.slice(k).join("."));b.push("none")}for(g=0;g<b.length;g++)if(f=b[g],w(c,h,e,d,f),w(c)==h)return a.set(K,
f),void(V=!0);a.set(K,"auto")}}function Ya(a){"cookie"!==J(a,ya)||V||(xa(a),V)||a.data.set(L,0)}function Za(a){if(100!==a.get(Q)&&q(J(a,L))%1E4>=100*wa(a,Q))throw r("samplerTask","current sampleRate is: ",a.get(Q)),"abort";}function $a(a){var b=[];P.map(function(c,d){if(d.protocolParameter){var f=a.get(c);0!==f&&f!=d.defaultValue&&("boolean"==typeof f&&(f*=1),b.push(d.protocolParameter+"="+encodeURIComponent(""+f)))}});b.push("z="+R());a.set(za,b.join("&"),!0)}function ab(a){var b=J(a,za),c=a.get(W);
switch(a.get(ha)){case "image":oa(b,c);break;case "cors":qa(b,c)||pa(b,c);break;case "iframe":ra(b,c);break;default:c=c||m,2036>=b.length?oa(b,c):!(8192>=b.length)||0<=x.userAgent.indexOf("Firefox")&&![].reduce?r("send","request param is to long ",b.length):qa(b,c)||pa(b,c)||ra(b,c)}a.set(W,m,!0)}function bb(a,b){var c=a.get(U),c=w(c);if(!b){if(!c){for(var c=x.appName+x.version+x.platform+x.userAgent+(e.cookie||"")+(e.referrer||""),d=c.length,f=g.history.length;0<f;)c+=f--^d++;c=[Math.round((new Date).getTime()/
1E3),R()^2147483647&q(c)].join("").substr(0,18)}b=c}a.data.set(L,b);xa(a)}function cb(a){var b="CSS1Compat"===e.compatMode?"documentElement":"body";if(a.set("referrer",Qa(a.get(ia))),E){var c=E.pathname||"";"/"!=c.charAt(0)&&(c="/"+c);a.set(db,E.protocol+"//"+E.hostname+c+E.search);X&&(a.set(eb,X.width+"*"+X.height),a.set(fb,X.colorDepth+"-bit"));a.set(gb,e[b].clientWidth+"*"+e[b].clientHeight);a.set(hb,Ra());a.set(ib,e.characterSet||e.charset);b="";c=!1;try{c=x&&p(x.javaEnabled)&&x.javaEnabled()||
!1}catch(d){r("collectClientInfo","javaEnabled error",d.message)}try{b=(x&&(x.language||x.browserLanguage)||"").toLowerCase()}catch(d){r("collectClientInfo","language error",d.message)}a.set(jb,c);a.set(kb,b)}}function lb(a){var b=g.performance||g.webkitPerformance,b=b&&b.timing;if(!b)return!1;var c=b.navigationStart;return 0===c?!1:(a[ja]=b.loadEventStart-c,a[Aa]=b.domainLookupEnd-b.domainLookupStart,a[Ba]=b.connectEnd-b.connectStart,a[Ca]=b.responseStart-b.requestStart,a[Da]=b.responseEnd-b.responseStart,
a[Ea]=b.fetchStart-c,a[Fa]=b.domInteractive-c,a[Ga]=b.domContentLoadedEventStart-c,!0)}function mb(a){if(g.top!=g)return!1;var b=g.external,c=b&&b.onloadT;return b&&!b.isValidLoadTime&&(c=void 0),2147483648<c&&(c=void 0),0<c&&b.setPageReadyTime(),void 0==c?!1:(a[ja]=c,!0)}function F(a,b){var c=a[b];(isNaN(c)||1/0==c||0>c)&&(a[b]=void 0)}function Ha(a,b){var c=Math.min(wa(a,ka),100);if(q(J(a,L))%100<c&&(c=[],lb(c)||mb(c))){var d=c[ja];void 0!=d&&isFinite(d)&&!isNaN(d)&&(0<d?(F(c,Aa),F(c,Ba),F(c,Ca),
F(c,Da),F(c,Ea),F(c,Fa),F(c,Ga),b(c)):A(g,"load",function(){Ha(a,b)},!1))}}function nb(a){a.timingIsSended||(a.timingIsSended=!0,Ha(a.storage,function(b){a.storage.set(Ia,!0,!0);a.send("timing",b)}))}function ob(a){function b(a,b){setTimeout(function(){a.storage.set(Ia,!0,!0);a.send("pulse")},1E3*b)}if(a.storage.get(la))for(var c=0;c<Ja.length;c++)b(a,Ja[c])}function Y(a){function b(a,b){d.storage.data.set(a,b)}function c(a,c){b(a,c);d.filters.add(a)}var d=this;d.storage=new T;d.filters=new ea;b(G,
a[G]);b(ma,a[ma]);b(U,a[U]);b(K,a[K]||u());b(fa,a[fa]);b(ga,a[ga]);b(Q,a[Q]);b(ha,a[ha]);b(ka,a[ka]);b(la,a[la]);b(ia,a[ia]);b(Ka,a[Ka]);c(pb,Xa);c(qb,Ya);c(rb,Za);c(sb,$a);c(tb,ab);bb(d.storage,a[L]);cb(d.storage);ob(d)}function Z(a,b){this.id=a;this.url=b;this.instance=this.factory=null;this.ready=this.loading=!1;this.queue=[];this.prefix="plugin_2015_";this.load()}function H(){this.plugins={}}function La(a){return-2<a.indexOf(".")+a.indexOf(":")}function ub(a){if(p(a[0]))this.ready=a[0];else{var b=
vb.exec(a[0]);if(null!=b&&4==b.length&&(this.name=b[1]||aa,this.pluginId=b[2]||"",this.action=b[3],this.opts=z.call(a,1)),!this.action)throw r("Env","no action"),"abort";if("require"===this.action&&(!k(a[1])||""===a[1]))throw r("Env","unexpected require arg: ",a[1]),"abort";if("provide"===this.action&&(!k(a[1])||""===a[1]))throw r("Env","unexpected provide arg: ",a[1]),"abort";if(La(this.pluginId)||La(this.action))throw r("Env","pluginId or action has  keyword ."),"abort";if("provide"===this.action&&
this.name!=aa)throw r("Env","provide not need trackerName"),"abort";}}function n(){C.append.apply(C,[arguments])}var X=g.screen,x=g.navigator,E=g.location,z=Array.prototype.slice,wb=Object.prototype.toString,B="",aa="t0",Sa="clickiLogStack2015",ta=3E3,ca=-1<E.hash.indexOf("clicki/debug/")||!1,Ja=[5,15,30],N=("https:"==E.protocol?"https:":"http:")+"//sm.gome.com.cn/",Ta="collect/track_proxy",ua="collect/track_ajax",Ua="collect/track_ajax",Va="collect_iframe.html";O.prototype.set=function(a,b,c){this.keys.push(a);
c?this.t2[":"+a]=b:this.t1[":"+a]=b};O.prototype.get=function(a){return this.t2.hasOwnProperty(":"+a)?this.t2[":"+a]:this.t1[":"+a]};O.prototype.map=function(a){for(var b=0;b<this.keys.length;b++){var c=this.keys[b],d=this.get(c);d&&a(c,d)}};var da=[],P=new O,t=S.prototype;t.init=function(){return this.data=[],this.dataLock=[],this.gestureCache=[],this.gestureBindLock=!1,this.binder="binderScroll binderKeydown binderResize binderMousedown binderMousemove binderSwipe binderTurn binderPinch".split(" "),
this.bindEvents(),this.reset(),this};t.bindEvents=function(){for(var a=0;a<this.binder.length;a++)this.dataLock[a]=!1,this[this.binder[a]](a)};t.onGesturesEventTrigger=function(a){var b=this.gestureCache;a=2<=(a.touches?a.touches.length:1)?"pinch":"swipe";for(var c=0;c<b.length;c++)b[c]&&b[c][0]===a&&this.onEventTrigger(b[c][1])};t.bindGesturesEvent=function(a,b){this.gestureCache.push([a,b]);var c="ontouchstart"in g;!this.gestureBindLock&&c&&e.addEventListener("touchmove",l(this.onGesturesEventTrigger,
this),!1)};t.onEventTrigger=function(a){this.dataLock[a]||(this.dataLock[a]=!0,this.data[a]=1)};t.binderScroll=function(a){A(g,"scroll",l(this.onEventTrigger,this,a))};t.binderKeydown=function(a){A(e,"keydown",l(this.onEventTrigger,this,a))};t.binderResize=function(a){A(g,"resize",l(this.onEventTrigger,this,a))};t.binderMousedown=function(a){A(e,"mousedown",l(this.onEventTrigger,this,a))};t.binderMousemove=function(a){A(e,"mousemove",l(this.onEventTrigger,this,a))};t.binderSwipe=function(a){this.bindGesturesEvent("swipe",
a)};t.binderTurn=function(a){g.orientation&&g.addEventListener("orientationchange",l(this.onEventTrigger,this,a),!1)};t.binderPinch=function(a){this.bindGesturesEvent("pinch",a)};t.reset=function(){for(var a=0;a<this.binder.length;a++)this.data[a]=0};t.get=function(){var a=this.data.join("-");return this.reset(),a};h("protocolVersion","v");var ma=v("trackingId","tid");h("anonymizeIp","aip");h("queueTime","qt");var ha=h("forceSendMethod"),L=v("clientId","cid"),Ka=h("userId","uid");h("miaozhenId","mzid");
h("sessionControl","sc","");h("referrer","dr");h("googleCampaignName","cn");h("googleCampaignSource","cs");h("googleCampaignMedium","cm");h("googleCampaignKeyword","ck");h("googleCampaignContent","cc");h("miaozhenCampaignId","mzc");h("miaozhenCampaignId","mzs");h("miaozhenCampaignId","mzk");I("customAds([0-9]+)",function(a){return new D(a[0],"ca"+a[1])});var eb=h("screenResolution","sr"),gb=h("viewportSize","vp"),ib=h("encoding","de"),fb=h("screenColors","sd"),kb=h("language","ul"),jb=h("javaEnabled",
"je"),hb=h("flashVersion","fl"),Ma=h("hitType","t"),Ia=h("nonInteraction","ni",void 0,function(a,b,c){return void 0==c?!1:c}),db=h("location","dl","");h("hostname","dh");var xb=h("page","dp","");h("title","dt",function(){return e.title||void 0});h("appName","an");h("appId","aid","");h("appVersion","av","");h("appInstallerId","aiid","");var yb=h("eventCategory","ec"),zb=h("eventAction","ea"),Ab=h("eventLabel","el"),Bb=h("eventValue","ev");h("customActionId","caid");I("customActionLabel([0-9]+)",function(a){return new D(a[0],
"cal"+a[1])});I("customActionValue([0-9]+)",function(a){return new D(a[0],"cav"+a[1])});I("dimension([0-9]+)",function(a){return new D(a[0],"cd"+a[1])});I("metric([0-9]+)",function(a){return new D(a[0],"cm"+a[1])});(function(a,b,c,d){return h(a,b,c,d,m)})("userBehavior","ub",void 0,l("get",S()));var W=h("hitCallback"),za=h("hitPayload"),Cb=h("socialNetwork","sn"),Db=h("socialAction","sa"),Eb=h("socialTarget","st"),ja=h("l1","plt"),Da=h("l2","pdt"),Aa=h("l3","dns"),Ea=h("l4","rrt"),Ca=h("l5","srt"),
Ba=h("l6","tcp"),Fa=h("l7","dit"),Ga=h("l8","clt"),Fb=h("timingCategory","utc"),Gb=h("timingVar","utv"),Hb=h("timingLabel","utl"),Ib=h("timingValue","utt"),G=v("name"),U=v("cookieName",void 0,"__clickidc"),K=v("cookieDomain"),fa=v("cookiePath",void 0,"/"),ga=v("cookieExpires",void 0,31536E4),ya=v("storage",void 0,"cookie"),la=v("sendPulse",void 0,!0),Q=v("sampleRate","sf",100),ka=v("siteSpeedSampleRate",void 0,10),ia=v("alwaysSendReferrer",void 0,!1),pb=h("checkProtocolTask"),qb=h("checkStorageTask"),
rb=h("samplerTask"),sb=h("buildHitTask"),tb=h("sendHitTask"),Na=!1;h("forceSSL",void 0,void 0,function(){return Na},function(a,b,c){Na=!!c});I("\\&(.*)",function(a){var b=new D(a[0],a[1]),c=Wa(a[0].substring(1));return c&&(b.getter=function(a){return a.get(c)},b.setter=function(a,b,c,e){a.set(b,c,e)},b.protocolParameter=void 0),b});T.prototype.clearTemp=function(){this.data.t2={}};T.prototype.get=function(a){var b=va(a),c=this.data.get(a);return b&&void 0==c&&(c=p(b.defaultValue)?b.defaultValue():
b.defaultValue),b&&p(b.getter)?b.getter(this,a,c):c};T.prototype.set=function(a,b,c){if(a)if("object"==typeof a)for(var d in a)a.hasOwnProperty(d)&&arguments.callee.call(this,d,a[d],c);else(d=va(a))&&p(d.setter)?d.setter(this,a,b,c):this.data.set(a,b,c)};ea.prototype.add=function(a){this.stack.push(a)};ea.prototype.run=function(a){try{for(var b=0;b<this.stack.length;b++){var c=a.get(this.stack[b]);p(c)&&c.call(g,a)}}catch(d){}b=a.get(W);b!=m&&(a.set(W,m,!0),setTimeout(b,10))};var V=!1;Y.prototype.get=
function(a){return this.storage.get(a)};Y.prototype.set=function(a,b){return this.storage.set(a,b),this};var Jb={pageview:[xb],event:[yb,zb,Ab,Bb],social:[Cb,Db,Eb],timing:[Fb,Gb,Hb,Ib]};Y.prototype.send=function(){var a,b;0<arguments.length&&(k(arguments[0])?(a=arguments[0],b=z.call(arguments,1)):(a=arguments[0]&&arguments[0][Ma],b=z.call(arguments)));a&&(b=na(Jb[a]||[],b),b[Ma]=a,this.storage.set(b,void 0,!0),this.filters.run(this.storage),"pageview"===a&&nb(this),this.storage.clearTemp())};Z.prototype.load=
function(){this.loading=!0;ba(this.url,this.prefix+this.id)};Z.prototype.provide=function(a,b){var c;this.factory=a;this.ready=!0;this.loading=!1;try{this.instance=new a(b)}catch(d){this.instance={},r("plugin provide","factory init error; plugin id is:",this.id,";error message is:",d.message)}for(;c=this.queue.shift();)this.use.apply(this,c)};Z.prototype.use=function(a,b){var c=this.instance;if(this.ready)try{c[a].apply(c,b)}catch(d){r("plugin use","action is: ",a,"; plugin id is:",this.id,";error message is:",
d.message)}else this.queue.push(z.call(arguments))};H.prototype.getAll=function(){return this.plugins};H.prototype.get=function(a){return this.plugins[a]};H.prototype.set=function(a,b){this.plugins[a]=b};H.prototype.use=function(a,b,c){(a=this.get(a))&&a.use&&a.use(b,c)};H.prototype.require=function(a,b){this.get(a)||this.set(a,new Z(a,b))};H.prototype.provide=function(a,b,c){var d=this.get(a);d&&d.provide&&d.provide.apply(d,z.call(arguments,1))};var vb=/^(?:(\w+)\.)?(?:(\w+):)?(\w+)$/,C={envs:[]};
C.pluginM=new H;C.process=function(){for(var a=[],b=0;b<arguments.length;b++)try{a.push(new ub(arguments[b]))}catch(c){}return a};C.run=function(a){try{if(a.ready)a.ready.call(g,n.getByName(aa));else{var b=n.getByName(a.name);if(a.pluginId)return this.pluginM.use(a.pluginId,a.action,a.opts);switch(a.action){case "create":n.create.apply(n,a.opts);break;case "remove":n.remove.call(n,a.name);break;case "require":this.pluginM.require.apply(this.pluginM,a.opts);break;case "provide":this.pluginM.provide.apply(this.pluginM,
a.opts.concat([b]));break;default:b[a.action].apply(b,a.opts)}}}catch(c){r("controller.run",c.message)}};C.append=function(){var a=this.process.apply(this,arguments),a=this.envs.concat(a);for(this.envs=[];a.length&&(this.run(a.shift()),!(0<this.envs.length)););this.envs=this.envs.concat(a)};var Oa=[],Pa=function(a,b,c){var d,f;return k(a[b])&&(f=a[b],d=f?f.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""),d||c}(g,"ClickiTrackerName","dc");n.lock=Oa;n.cache={};n.start=0;n.stack=[];var Kb=[ma,K,
G];n.create=function(){var a=na(Kb,z.call(arguments));a[G]||(a[G]=aa);var b=""+a[G];if(n.cache[b])return n.cache[b];a=new Y(a);return n.cache[b]=a,n.stack.push(a),a};n.remove=function(a){for(var b=0;b<n.stack.length;b++)if(n.stack[b].get(G)==a){n.stack.splice(b,1);n.cache[a]=null;break}};n.getAll=function(){return n.stack.slice(0)};n.getByName=function(a){return n.cache[a]};n.init=function(){var a=g[Pa];a&&a.lock==Oa||(ca=!!a.debug,B=a.debugSendUrl,n.loaded=!0,n.start=a&&a.start,g[Pa]=n,a=a&&a.queue,
"[object Array]"==wb.call(Object(a))&&C.append.apply(C,a))};n.init()}(window,document);
(function(){function g(e){var g=new Date,k=arguments;if(1<k.length){var m=k[2]||0,p=k[3]||"/",y=k[4]||0,ba=k[5]||0;m&&g.setTime(g.getTime()+1E3*m);document.cookie=e+"="+escape(k[1])+(m?"; expires="+g.toGMTString():"")+("; path="+p)+(y?"; domain="+y:"")+(ba?"; secure":"");return k[1]}return(g=document.cookie.match("(?:^|;)\\s*"+e+"=([^;]*)"))?unescape(g[1]):0}for(var e=g("__clickidc"),y=g("__c_visitor"),m=document.domain.split("."),p=[],k=m.length-2;0<=k;k--)p.push(m.slice(k).join("."));for(k=0;k<
p.length&&(y?g("__c_visitor",y,31536E4,"/",p[k]):g("__c_visitor",e,31536E4,"/",p[k]),g("__clickidc")!=g("__c_visitor"));k++);})();